spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      #authentication-database: admin
      #username: root
      #password: example
      database: circuit-breaker

client:
  comments:
    url: http://localhost:8082

management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true

resilience4J.circuitbreaker:
  instances:
    comments:
      slidingWindowSize: 8                          # quantidade de chamadas monitoradas para inicar o circuit
      #slowCallDurationThreshold: 2000               # controla o circuit por tempo de response
      slowCallRateThreshold: 10                     # limita de taxa das chamadas lentas  %
      minimumNumberOfCalls: 4                      # controla o circuit pelo numero de chamadas com falhas
      #permittedNumberOfCallsInHalfOpenState: 2     # quantidade de chamadas para mudar do semi aberto para o aberto
      waitDurationInOpenState: 30s                 # tempo de duração que o circuito fica aberto



